[package]
name = "rusqlite-geob"
version = "0.1.0"
edition = "2024"

[features]
default = ["index"]
proj = ["geob/proj"]
index = ["rstar"]

[dependencies]
geob = { path = "../geob", features = ["geo-traits", "sqlite", "rstar"] }
rusqlite = { workspace = true, features = ["functions", "vtab"] }

geo-traits = { workspace = true }
geo = { workspace = true }

udled = { version = "0.6" }
udled-tokenizers = { version = "0.5" }

rstar = { workspace = true, optional = true }

bitflags = { version = "2" }
